# Generated by Django 5.1.3 on 2024-11-10 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
