# Generated by Django 5.1.3 on 2024-11-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_usuario_mensaje_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
